//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;
import typecheck.*;

public class MakeGraph extends GJNoArguDepthFirst<String>{
    // create a map of each Class to its unique ID (starts from 1)
    HashMap<String, Integer> classID;
    ArrayList<String> className;
    ArrayList<Node> classNode;
    ArrayList<String> parent;
    ArrayList<ArrayList<Method>> methodList;
    Node mainClass;

    // DEBUG VARIABLES
    boolean printOutput;
    int scope;
    boolean debug;
    boolean graphDebug;

    // constructor
    public MakeGraph(){
        classID = new HashMap<String, Integer>();
        className = new ArrayList<String>();
        classNode = new ArrayList<Node>();
        parent = new ArrayList<String>();
        methodList = new ArrayList<ArrayList<Method>>();
        mainClass = null;
        debug = false;
        printOutput = true;
        graphDebug = true;
        scope = 0;
    }


    private void printTabs() {
        for(int i=0; i<scope; i++)
            System.out.print("\t");
    }

    public String visit(NodeToken n){
         if(!debug || !printOutput)
             return null;

         System.out.print(n.tokenImage+" ");
         if(n.tokenImage=="{") 
             scope++;
         else if(n.tokenImage=="}")
             scope--;
         if(n.tokenImage=="}"||n.toString()=="{"||n.toString()==";"){
             System.out.println("");
             printTabs();
         }
         return null;
    }

///////////////// PRODUCTIONS //////////////////

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "{"
    * f3 -> "public"
    * f4 -> "static"
    * f5 -> "void"
    * f6 -> "main"
    * f7 -> "("
    * f8 -> "String"
    * f9 -> "["
    * f10 -> "]"
    * f11 -> Identifier()
    * f12 -> ")"
    * f13 -> "{"
    * f14 -> PrintStatement()
    * f15 -> "}"
    * f16 -> "}"
    */
   public String visit(MainClass n) {
      mainClass = n;
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
      n.f7.accept(this);
      n.f8.accept(this);
      n.f9.accept(this);
      n.f10.accept(this);
      n.f11.accept(this);
      n.f12.accept(this);
      n.f13.accept(this);
      n.f14.accept(this);
      n.f15.accept(this);
      n.f16.accept(this);
      int index = className.size();
      String name = n.f1.f0.tokenImage;
      className.add(name);
      if(classID.containsKey(name))
          (new ErrorFunc()).throwTypeError("Class already present"+name);
      classID.put(name, index);
      classNode.add(n);
      parent.add(null);
      methodList.add(new ArrayList<Method>());
      Method newMethod = (new Method(name, "main", "void"));
      newMethod.addArgument(n.f11.f0.tokenImage,"String[]");
      methodList.get(index).add(newMethod);
      return null;
   }

    public String visit(ClassDeclaration n){
       n.f0.accept(this);
       n.f1.accept(this);
       int index = className.size();
       String name = n.f1.f0.tokenImage;
       className.add(name);
       if(classID.containsKey(name))
           (new ErrorFunc()).throwMultiDeclError(name);
       classID.put(name, index);
       classNode.add(n);
       parent.add(null);
       methodList.add(new ArrayList<Method>());
       n.f2.accept(this);
       n.f3.accept(this);
       n.f4.accept(this);
       n.f5.accept(this);
       return null;
    }

    public String visit(ClassExtendsDeclaration n){
       n.f0.accept(this);
       n.f1.accept(this);
       n.f2.accept(this);
       n.f3.accept(this);
       int index = className.size();
       String name = n.f1.f0.tokenImage;
       className.add(name);
       if(classID.containsKey(name))
           (new ErrorFunc()).throwTypeError("Class already present"+name);
       classID.put(name, index);
       classNode.add(n);
       parent.add(n.f3.f0.tokenImage);
       methodList.add(new ArrayList<Method>());
       n.f4.accept(this);
       n.f5.accept(this);
       n.f6.accept(this);
       n.f7.accept(this);
       return null;
    }

   /**
    * f0 -> "public"
    * f1 -> Type()
    * f2 -> Identifier()
    * f3 -> "("
    * f4 -> ( FormalParameterList() )?
    * f5 -> ")"
    * f6 -> "{"
    * f7 -> ( VarDeclaration() )*
    * f8 -> ( Statement() )*
    * f9 -> "return"
    * f10 -> Expression()
    * f11 -> ";"
    * f12 -> "}"
    */
   public String visit(MethodDeclaration n) {
      n.f0.accept(this);
      String returnType = n.f1.accept(this);
      String methodName = n.f2.accept(this);
      int len = className.size();
      String thisClassName = className.get(len-1);
      methodList.get(len-1).add(new Method(thisClassName, methodName, returnType));
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
      n.f7.accept(this);
      n.f8.accept(this);
      n.f9.accept(this);
      n.f10.accept(this);
      n.f11.accept(this);
      n.f12.accept(this);
      return null;
   }
    
    /**
    * f0 -> Type()
    * f1 -> Identifier()
    */
   public String visit(FormalParameter n) {
      String varType = n.f0.accept(this);
      String varName = n.f1.accept(this);
      int lenClass = className.size();
      int lenMethod = methodList.get(lenClass-1).size();
      methodList.get(lenClass-1).get(lenMethod-1).addArgument(varName, varType);
      return null;
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public String visit(Identifier n) {
      n.f0.accept(this);
      return n.f0.tokenImage;
   }
   

   /**
    * f0 -> ArrayType()
    *       | BooleanType()
    *       | IntegerType()
    *       | Identifier()
    */
   public String visit(Type n) {
      return n.f0.accept(this);
   }

   /**
    * f0 -> "int"
    * f1 -> "["
    * f2 -> "]"
    */
   public String visit(ArrayType n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      return "int[]";
   }

   /**
    * f0 -> "boolean"
    */
   public String visit(BooleanType n) {
      n.f0.accept(this);
      return "boolean";
   }

   /**
    * f0 -> "int"
    */
   public String visit(IntegerType n) {
      n.f0.accept(this);
      return "int";
   }

//////////////// PRODUCTIONS-END //////////////////

    public void showArray(){
        if(!debug)
            return;
        System.out.println("Classes are : ");
        for(int i=0; i<className.size(); i++)
            System.out.print(className.get(i)+" ");
        System.out.println("");
    }

    private ArrayList<Integer> makeIDVector(){
        ArrayList<Integer> par = new ArrayList<>();
        for(int i=0; i<parent.size(); i++){
           if(parent.get(i)==null){
               par.add(null);
               continue;
           }
           if(!classID.containsKey(parent.get(i)))
                (new ErrorFunc()).throwSymbolError(parent.get(i)+"ClassError");
           par.add(classID.get(parent.get(i)));
        }
        if(debug && graphDebug){
            for(int i=0; i<par.size(); i++){
                if(par.get(i)==null)
                    continue;
                System.out.println("Parent of "+className.get(i)+" is "+className.get(par.get(i)));
            }
        }
        return par;
    }

    public ArrayList<TreeNode> createGraph(){
        ArrayList<ArrayList<Node>> graph = new ArrayList<>();

        // Get the ID -> parentID vector
        ArrayList<Integer> parentID = makeIDVector();

        // Now make adjacency list
        ArrayList<ArrayList<Integer>> adjList = new ArrayList<>();
        for(int i=0; i<parentID.size(); i++)
            adjList.add(new ArrayList<Integer>());
        for(int i=0; i<parentID.size(); i++)
            if(parentID.get(i)!=null){
                adjList.get(parentID.get(i)).add(i);
                if(parentID.get(i)==i)
                    (new ErrorFunc()).throwTypeError("Class extends itself");
            }
            

        // DEBUG print the graph
        if(debug && graphDebug){
            for(int i=0; i<adjList.size(); i++){
                System.out.print("Derived from Class "+className.get(i)+": ");
                for(int j=0; j<adjList.get(i).size(); j++){
                    System.out.print(className.get(adjList.get(i).get(j))+" ");
                }
                System.out.println("");
            }
        }

        // Make the trees using the adjLists
        ArrayList<TreeNode> forest = new ArrayList<>();
         // create a TreeNode for each class
        ArrayList<TreeNode> classTreeNode = new ArrayList<>();
        for(int i=0; i<classNode.size(); i++)
            classTreeNode.add(new TreeNode(classNode.get(i)));
         // Populate their children
        for(int i=0; i<classNode.size(); i++)
            for(int j=0; j<adjList.get(i).size(); j++)
                classTreeNode.get(i).addChild(classTreeNode.get(adjList.get(i).get(j)));
         // Add roots to forest
        for(int i=0; i<parent.size(); i++)
            if(parent.get(i)==null)
                forest.add(classTreeNode.get(i));

        return forest;
    }

    public int getNumberOfClasses(){
       if(debug){
           for(ArrayList<Method> l : methodList)
               for(Method m : l)
                   m.print();
       }
        return className.size();
    }

    public boolean isValidClass(String classname){
        return classID.containsKey(classname);
    }

    public ArrayList<Method> getMethodList(String nameOfClass){
        for(int i=0; i<className.size(); i++)
            if(className.get(i)==nameOfClass){
                return methodList.get(i);
            }
        return null;
    }

    public boolean isParent(String par, String ch){
       if(ch==par)
           return true;
       String cur = ch;
       int curIndex = -1;
       if(!classID.containsKey(ch))
           return false;
       curIndex = classID.get(ch);
       while(parent.get(curIndex)!=null){
           if(debug){
                System.out.println(par);
                System.out.flush();
           }
            cur = parent.get(curIndex);
            if(cur==par)
                return true;
            if(!classID.containsKey(cur))
                return false;
            curIndex = classID.get(cur);
       }
       return false;
    }

    public Node getMainClass(){
        return mainClass;
    }

    private Method getMethodRecursive(String nameOfClass, String nameOfMethod){
        if(debug)
            System.out.println("Searching in "+nameOfClass+" for "+nameOfMethod);
        if(nameOfClass==null){
            if(debug)
                System.out.println("Could not find ");
            return null;
        }
        int id = classID.get(nameOfClass);
        ArrayList<Method> mList = methodList.get(id);
        for(int i=0; i<mList.size(); i++)
            if(mList.get(i).name==nameOfMethod)
                return mList.get(i);
        return getMethodRecursive(parent.get(id), nameOfMethod);
    }

    public Method getMethod(String nameOfClass, String nameOfMethod){
        return getMethodRecursive(nameOfClass, nameOfMethod);
    }
}
