//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * Synthesized Attribute addr are stored in the HashMaps
 * Inherited Attributes are passed as arguments
 * Expression returns the type of the expression 
 */
public class GenIR extends GJDepthFirst<String,String> {

   /**
    * Global Variables
    */
   MicroIR ir;
   String currClass;
   HashMap<String, ClassData> classData;
   boolean debug;
   int scope;

   /**
    * Attribute Maps of Nodes
    */
   HashMap<Node, Integer> addr;

   /**
    * Current Method related variables
    */
   String currMethod;
   HashMap<String, Integer> localVars;
   int tempCount;
   int labelCount;
   ArrayList<Integer> argList;
   HashMap<String, String> localVarsType;

   public GenIR(MicroIR ir, HashMap<String, ClassData> classData, boolean debug){
      scope = 0;
      this.debug = debug;
      this.ir = ir;
      currClass = null;
      currMethod = null;
      this.classData = classData;
      addr = new HashMap<>();
      localVars = new HashMap<>();
      localVarsType = new HashMap<>();
      tempCount = 0;
      labelCount = 0;
      argList = new ArrayList<>();
   }

   int fresh(){
      return tempCount++;
   }

   String freshLabel(){
      return "L" + labelCount++;
   }

   
   // for printing
    private void printTabs() {
        for(int i=0; i<scope; i++)
            System.out.print("\t");
    }

    public String visit(NodeToken n, String argu){
         if(!debug)
             return null;

         System.out.print(n.tokenImage+" ");
         if(n.tokenImage=="{") 
             scope++;
         else if(n.tokenImage=="}")
             scope--;
         if(n.tokenImage=="}"||n.toString()=="{"||n.toString()==";"){
             System.out.println("");
             printTabs();
         }
         return null;
    }

   /**
    * f0 -> MainClass()
    * f1 -> ( TypeDeclaration() )*
    * f2 -> <EOF>
    */
   public String visit(Goal n, String argu) {
      String _ret=null;
      ir.genNoNOOP("MAIN");
      n.f0.accept(this, argu);
      ir.genNoNOOP("END");
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "{"
    * f3 -> "public"
    * f4 -> "static"
    * f5 -> "void"
    * f6 -> "main"
    * f7 -> "("
    * f8 -> "String"
    * f9 -> "["
    * f10 -> "]"
    * f11 -> Identifier()
    * f12 -> ")"
    * f13 -> "{"
    * f14 -> PrintStatement()
    * f15 -> "}"
    * f16 -> "}"
    */
   public String visit(MainClass n, String argu) {
      String _ret=null;
      labelCount = 0;
      tempCount = 0;
      n.f14.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "{"
    * f3 -> ( VarDeclaration() )*
    * f4 -> ( MethodDeclaration() )*
    * f5 -> "}"
    */
   public String visit(ClassDeclaration n, String argu) {
      String _ret=null;
      currClass = n.f1.f0.tokenImage;
      if(debug){
         System.out.println("Class: " + currClass);
      }
      n.f4.accept(this, argu);
      currClass = null;
      return _ret;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "extends"
    * f3 -> Identifier()
    * f4 -> "{"
    * f5 -> ( VarDeclaration() )*
    * f6 -> ( MethodDeclaration() )*
    * f7 -> "}"
    */
   public String visit(ClassExtendsDeclaration n, String argu) {
      String _ret=null;
      currClass = n.f1.f0.tokenImage;
      if(debug){
         System.out.println("Class: " + currClass);
      }
      n.f6.accept(this, argu);
      currClass = null;
      return _ret;
   }

   /**
    * f0 -> Type()
    * f1 -> Identifier()
    * f2 -> ";"
    */
   public String visit(VarDeclaration n, String argu) {
      String _ret=null;
      String retType = n.f0.accept(this, "Decl");
      n.f1.accept(this, "Decl");
      // add to localVars
      // !TODO: should we initialise to 0?
      int reg = fresh();
      localVars.put(n.f1.f0.tokenImage, reg);
      ir.genMoveTempConst(reg, 0);
      localVarsType.put(n.f1.f0.tokenImage, retType);
      return _ret;
   }

   /**
    * f0 -> ArrayType()
    *       | BooleanType()
    *       | IntegerType()
    *       | Identifier()
    */
   public String visit(Type n, String argu) {
      String _ret=null;
      _ret = n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "int"
    * f1 -> "["
    * f2 -> "]"
    */
   public String visit(ArrayType n, String argu) {
      return "int[]";
   }

   /**
    * f0 -> "boolean"
    */
   public String visit(BooleanType n, String argu) {
      return "boolean";
   }

   /**
    * f0 -> "int"
    */
   public String visit(IntegerType n, String argu) {
      return "int";
   }

   /**
    * f0 -> "public"
    * f1 -> Type()
    * f2 -> Identifier()
    * f3 -> "("
    * f4 -> ( FormalParameterList() )?
    * f5 -> ")"
    * f6 -> "{"
    * f7 -> ( VarDeclaration() )*
    * f8 -> ( Statement() )*
    * f9 -> "return"
    * f10 -> Expression()
    * f11 -> ";"
    * f12 -> "}"
    */
   public String visit(MethodDeclaration n, String argu) {
      String _ret=null;
      // n.f0.accept(this, argu);
      // n.f1.accept(this, argu);
      // n.f2.accept(this, argu);
      currMethod = n.f2.f0.tokenImage;
      localVars.clear();
      localVarsType.clear();
      tempCount = 1;
      argList.clear();
      // labelCount = 0; // !TODO: Should this be cleared?
      // n.f3.accept(this, argu);
      ir.genStartMethod(currClass, currMethod, localVars.size()+1);
      n.f4.accept(this, "FormalParameters");
      if(debug){
         ir.printIR();
      }
      // n.f5.accept(this, argu);
      // n.f6.accept(this, argu);
      n.f7.accept(this, argu);
      n.f8.accept(this, argu);
      n.f9.accept(this, argu);
      n.f10.accept(this, argu);
      ir.genNoNOOP(" RETURN ");
      ir.genNoNOOP("TEMP "+addr.get(n.f10));
      // n.f11.accept(this, argu);
      // n.f12.accept(this, argu);
      ir.genEndMethod();
      currMethod = null;
      return _ret;
   }

   /**
    * f0 -> Type()
    * f1 -> Identifier()
    */
   public String visit(FormalParameter n, String argu) {
      String _ret=null;
      // !TODO: Initialise formal parameters NEVER INITIALISE PARAMS
      String parType = n.f0.accept(this, "Decl");
      n.f1.accept(this, argu);
      // add to localVars
      int reg = fresh();
      localVars.put(n.f1.f0.tokenImage, reg);
      // ir.genMoveTempConst(reg, 0);
      localVarsType.put(n.f1.f0.tokenImage, parType);
      return _ret;
   }

   /**
    * f0 -> Identifier()
    * f1 -> "="
    * f2 -> Expression()
    * f3 -> ";"
    */
   public String visit(AssignmentStatement n, String argu) {
      String _ret=null;
      n.f0.accept(this, "Assignment");
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      String varname = n.f0.f0.tokenImage;
      Integer regExp = addr.get(n.f2);
      if(localVars.containsKey(varname)){
         // local var
         Integer reg = localVars.get(varname);
         ir.genMoveTempTemp(reg, regExp);
      }
      else{
         // must be a class field
         Integer offset = classData.get(currClass).getVarPosition(varname);
         ir.genHStore(0, 4*(offset+1), regExp);
      }
      return _ret;
   }

   /**
    * f0 -> Identifier()
    * f1 -> "["
    * f2 -> Expression()
    * f3 -> "]"
    * f4 -> "="
    * f5 -> Expression()
    * f6 -> ";"
    */
   public String visit(ArrayAssignmentStatement n, String argu) {
      String _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      // String varname = n.f0.f0.tokenImage;
      Integer regExp1 = addr.get(n.f2);
      Integer regExp2 = addr.get(n.f5);

      Integer offset = fresh();
      ir.genBinOp(offset, "TIMES", regExp1, "4");
      ir.genBinOp(offset, "PLUS", offset, "4");

      int arr = addr.get(n.f0);
      int newarr = fresh();
      ir.genBinOp(newarr, "PLUS", arr, " TEMP "+offset);
      ir.genHStore(newarr, 0, regExp2);

      return _ret;
   }

   /**
    * f0 -> "if"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    */
   public String visit(IfthenStatement n, String argu) {
      String _ret=null;
      String label1 = freshLabel();
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      Integer regExp = addr.get(n.f2);
      ir.genCJump(regExp, label1);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      ir.gen(label1);
      return _ret;
   }

   /**
    * f0 -> "if"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    * f5 -> "else"
    * f6 -> Statement()
    */
   public String visit(IfthenElseStatement n, String argu) {
      String _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);

      String label1 = freshLabel();
      String label2 = freshLabel();
      Integer regExp = addr.get(n.f2);
      ir.genCJump(regExp, label1);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      ir.genJump(label2);
      ir.gen(label1);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      ir.gen(label2);

      return _ret;
   }

   /**
    * f0 -> "while"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    */
   public String visit(WhileStatement n, String argu) {
      String _ret=null;

      String label1 = freshLabel();
      String label2 = freshLabel();
      ir.gen(label1);
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      Integer regExp = addr.get(n.f2);
      ir.genCJump(regExp, label2);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      ir.genJump(label1);
      ir.gen(label2);
      return _ret;
   }

   /**
    * f0 -> "do"
    * f1 -> Statement()
    * f2 -> "while"
    * f3 -> "("
    * f4 -> Expression()
    * f5 -> ")"
    * f6 -> ";"
    */
   public String visit(DoStatement n, String argu) {
      String _ret=null;

      String label1 = freshLabel();
      String label2 = freshLabel();
      ir.gen(label1);
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      int regExp = addr.get(n.f4);
      ir.genCJump(regExp, label2);
      ir.genJump(label1);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      ir.gen(label2);
      return _ret;
   }

   /**
    * f0 -> "System.out.println"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> ";"
    */
   public String visit(PrintStatement n, String argu) {
      String _ret=null;
      n.f0.accept(this, argu);
      // n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      // n.f3.accept(this, argu);
      // n.f4.accept(this, argu);
      Integer reg = addr.get(n.f2);
      if(debug){
         System.out.println(reg);
      }
      ir.genPrint(reg);
      return _ret;
   }

   /**
    * f0 -> OrExpression()
    *       | AndExpression()
    *       | CompareExpression()
    *       | neqExpression()
    *       | AddExpression()
    *       | MinusExpression()
    *       | TimesExpression()
    *       | DivExpression()
    *       | ArrayLookup()
    *       | ArrayLength()
    *       | MessageSend()
    *       | PrimaryExpression()
    */
   public String visit(Expression n, String argu) {
      String _ret=null;
      _ret = n.f0.accept(this, argu);
      addr.put(n, addr.get(n.f0.choice));
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "&&"
    * f2 -> PrimaryExpression()
    */
   public String visit(AndExpression n, String argu) {
      String _ret=null;
      ir.genSingleLineComment("First Boolean Evaluation of && starts here");
      n.f0.accept(this, argu);
      ir.genSingleLineComment("First Boolean Evaluation of && ends here");
      n.f1.accept(this, argu);
      int regExp1 = addr.get(n.f0);
      int regAns = fresh();
      String label1 = freshLabel();
      String label2 = freshLabel();

      ir.genCJump(regExp1, label1);
      ir.genSingleLineComment("Second Boolean Evaluation of && starts here");
      n.f2.accept(this, argu);
      ir.genSingleLineComment("Second Boolean Evaluation of && end here");
      int regExp2 = addr.get(n.f2);
      ir.genCJump(regExp2, label1);
      ir.genMoveTempConst(regAns, 1);
      ir.genJump(label2);
      ir.gen(label1);
      ir.genMoveTempConst(regAns, 0);
      ir.gen(label2);
      ir.genSingleLineComment("Complete Boolean Evaluation of && ends here");

      addr.put(n, regAns);

      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "||"
    * f2 -> PrimaryExpression()
    */
   public String visit(OrExpression n, String argu) {
      String _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);

      int regExp1 = addr.get(n.f0);
      int regAns = fresh();
      String label1 = freshLabel();
      String label2 = freshLabel();
      String label3 = freshLabel();
      String label4 = freshLabel();

      ir.genCJump(regExp1, label2);
      ir.gen(label1);
      ir.genMoveTempConst(regAns, 1);
      ir.genJump(label4);
      ir.gen(label2);
      n.f2.accept(this, argu);
      int regExp2 = addr.get(n.f2);
      ir.genCJump(regExp2, label3);
      ir.genJump(label1);
      ir.gen(label3);
      ir.genMoveTempConst(regAns, 0);
      ir.gen(label4);

      addr.put(n, regAns);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "<="
    * f2 -> PrimaryExpression()
    */
   public String visit(CompareExpression n, String argu) {
      String _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);

      int regExp1 = addr.get(n.f0);
      int regExp2 = addr.get(n.f2);
      int regAns = fresh();

      ir.genBinOp(regAns, "LE", regExp1, "TEMP "+regExp2);
      addr.put(n, regAns);

      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "!="
    * f2 -> PrimaryExpression()
    */
   public String visit(neqExpression n, String argu) {
      String _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);

      int regExp1 = addr.get(n.f0);
      int regExp2 = addr.get(n.f2);
      int regAns = fresh();
      ir.genBinOp(regAns, "NE", regExp1, "TEMP "+regExp2);
      addr.put(n, regAns);

      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "+"
    * f2 -> PrimaryExpression()
    */
   public String visit(AddExpression n, String argu) {
      String _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);

      if(debug){
         // print the first primary exp
         System.out.println("AddExpression");
         System.out.println("f0: "+n.f0.toString());
      }
      int regExp1 = addr.get(n.f0);
      int regExp2 = addr.get(n.f2);
      int regAns = fresh();
      ir.genBinOp(regAns, "PLUS", regExp1, "TEMP "+regExp2);
      addr.put(n, regAns);

      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "-"
    * f2 -> PrimaryExpression()
    */
   public String visit(MinusExpression n, String argu) {
      String _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);

      int regExp1 = addr.get(n.f0);
      int regExp2 = addr.get(n.f2);
      int regAns = fresh();
      ir.genBinOp(regAns, "MINUS", regExp1, "TEMP "+regExp2);
      addr.put(n, regAns);

      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "*"
    * f2 -> PrimaryExpression()
    */
   public String visit(TimesExpression n, String argu) {
      String _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);

      int regExp1 = addr.get(n.f0);
      int regExp2 = addr.get(n.f2);
      int regAns = fresh();
      ir.genBinOp(regAns, "TIMES", regExp1, "TEMP "+regExp2);
      addr.put(n, regAns);

      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "/"
    * f2 -> PrimaryExpression()
    */
   public String visit(DivExpression n, String argu) {
      String _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);

      int regExp1 = addr.get(n.f0);
      int regExp2 = addr.get(n.f2);
      int regAns = fresh();
      ir.genBinOp(regAns, "DIV", regExp1, "TEMP "+regExp2);
      addr.put(n, regAns);

      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "["
    * f2 -> PrimaryExpression()
    * f3 -> "]"
    */
   public String visit(ArrayLookup n, String argu) {
      String _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);

      int regExp1 = addr.get(n.f0);
      int regExp2 = addr.get(n.f2);
      int regAddr = fresh();
      int regAns = fresh();

      ir.genSingleLineComment("Starting Array Lookup");
      int regLen = fresh();
      ir.genBinOp(regLen, "TIMES", regExp2, "4");
      ir.genBinOp(regLen, "PLUS", regLen, "4");
      ir.genBinOp(regAddr, "PLUS", regExp1, "TEMP "+regLen);
      ir.genHLoad(regAns, regAddr, 0);
      ir.genSingleLineComment("Ending Array Lookup");

      addr.put(n, regAns);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "."
    * f2 -> "length"
    */
   public String visit(ArrayLength n, String argu) {
      String _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);

      // !TODO: What to return here
      int regExp1 = addr.get(n.f0);
      int regAns = fresh();
      ir.genHLoad(regAns, regExp1, 0);
      
      addr.put(n, regAns);

      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "."
    * f2 -> Identifier()
    * f3 -> "("
    * f4 -> ( ExpressionList() )?
    * f5 -> ")"
    */
   public String visit(MessageSend n, String argu) {
      String _ret=null;
      argu = null;
      String objClass = n.f0.accept(this, null);
      // this is wrong
      // if(localVars.containsKey(objClass)){
      //    objClass = localVarsType.get(objClass);
      // }
      // else{
      //    // its already the className
      //    ;
      // }
      if(objClass.charAt(0)!='@'){
         // This is completely redundant
         
         // means its a local variable
         if(localVarsType.containsKey(objClass)){
            objClass = localVarsType.get(objClass);
         }
         else{
            objClass = classData.get(currClass).getVarType(objClass);
         }
      }
      else{
         // remove the @
         objClass = objClass.substring(1);
      }

      // store the current argList
      ArrayList<Integer> oldArgList = argList;
      argList = new ArrayList<Integer>();
      argList.add(addr.get(n.f0));

      n.f1.accept(this, argu);
      n.f2.accept(this, "MessageSend");

      // get the method name
      String calledMethodName = n.f2.f0.toString();

      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);

      int regFunc = fresh();

      // get the function
      if(debug){
         System.out.println("objClass: "+objClass);
         System.out.println("calledMethodName: "+calledMethodName);
         // System.out.println("funcOffset: "+objClassData.getMethodPosition(calledMethodName));
         System.out.flush();
      }
      ClassData objClassData = classData.get(objClass);
      if(debug){
         System.out.println("funcOffset: "+objClassData.getMethodPosition(calledMethodName));
         System.out.flush();
      }
      int funcOffset = objClassData.getMethodPosition(calledMethodName);
      int regVTable = fresh();
      ir.genHLoad(regVTable, addr.get(n.f0), 0);
      ir.genHLoad(regFunc, regVTable, funcOffset*4);

      // call the function
      int regAns = fresh();
      ir.genCall(regAns, regFunc, argList);

      addr.put(n, regAns);

      // restore the argList
      argList = oldArgList;

      if(debug){
         // print return type
         System.out.println("return type: "+objClassData.getReturnType(calledMethodName));
      }
      return "@"+objClassData.getReturnType(calledMethodName);
   }

   /**
    * f0 -> Expression()
    * f1 -> ( ExpressionRest() )*
    */
   public String visit(ExpressionList n, String argu) {
      String _ret=null;
      n.f0.accept(this, argu);
      // add the expression to the argList
      argList.add(addr.get(n.f0));
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ","
    * f1 -> Expression()
    */
   public String visit(ExpressionRest n, String argu) {
      String _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      // add the expression to the argList
      argList.add(addr.get(n.f1));
      return _ret;
   }

   /**
    * f0 -> IntegerLiteral()
    *       | TrueLiteral()
    *       | FalseLiteral()
    *       | Identifier()
    *       | ThisExpression()
    *       | ArrayAllocationExpression()
    *       | AllocationExpression()
    *       | NotExpression()
    *       | BracketExpression()
    */
   public String visit(PrimaryExpression n, String argu) {
      String _ret=null;
      _ret = n.f0.accept(this, argu);
      
      // store the register of the primary expression
      // !CHANGE
      int regExpr = addr.get(n.f0.choice);
      int regAns = fresh();
      ir.genMoveTempTemp(regAns, regExpr);
      addr.put(n, regAns);

      if(debug){
         System.out.println("PrimaryExpression: "+_ret);
      }
      return _ret;
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public String visit(IntegerLiteral n, String argu) {
      String _ret=null;
      n.f0.accept(this, argu);

      int regAns = fresh();
      ir.genMoveTempConst(regAns, Integer.parseInt(n.f0.toString()));
      addr.put(n, regAns);

      return _ret;
   }

   /**
    * f0 -> "true"
    */
   public String visit(TrueLiteral n, String argu) {
      String _ret=null;
      n.f0.accept(this, argu);

      int regAns = fresh();
      ir.genMoveTempConst(regAns, 1);
      addr.put(n, regAns);

      return _ret;
   }

   /**
    * f0 -> "false"
    */
   public String visit(FalseLiteral n, String argu) {
      String _ret=null;
      n.f0.accept(this, argu);

      int regAns = fresh();
      ir.genMoveTempConst(regAns, 0);
      addr.put(n, regAns);

      return _ret;
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public String visit(Identifier n, String argu) {
      String _ret=null;
      n.f0.accept(this, argu);

      if(debug){
         System.out.println("Identifier "+n.f0.toString());
         System.out.println("Argument: "+argu);
      }

      if(argu!=null)
         return n.f0.tokenImage;

      String varname = n.f0.toString();
      if(localVars.containsKey(varname)){
         // local variable
         addr.put(n, localVars.get(varname));
         return "@"+localVarsType.get(varname);
      }
      else{
         // must be a class variable
         if(debug){
            System.out.println("Class variable "+varname);
            System.out.println("Class "+currClass);
         }
         int offset = classData.get(currClass).getVarPosition(varname);
         int regAns = fresh();
         ir.genHLoad(regAns, 0, (offset+1)*4);
         addr.put(n, regAns);
         return "@"+classData.get(currClass).getVarType(varname);
      }
   }

   /**
    * f0 -> "this"
    */
   public String visit(ThisExpression n, String argu) {
      String _ret=null;
      n.f0.accept(this, argu);
      addr.put(n, 0);
      return "@"+currClass;
   }

   /**
    * f0 -> "new"
    * f1 -> "int"
    * f2 -> "["
    * f3 -> Expression()
    * f4 -> "]"
    */
   public String visit(ArrayAllocationExpression n, String argu) {

      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);

      // store the size of the array
      // !TODO: Initialise with zeroes
      int regSizeOG = addr.get(n.f3);
      int regSizePlus4 = fresh();
      int regAns = fresh();
      int regSize = fresh();
      ir.genBinOp(regSize, "TIMES", regSizeOG, "4");
      ir.genBinOp(regSizePlus4, "PLUS", regSize, " 4");
      ir.genMoveTempString(regAns, " HALLOCATE TEMP "+regSizePlus4);
      ir.genHStore(regAns, 0, regSizeOG);

      // initialise with zeroes (Assuming array size is atleast 1)
      int regLoop = fresh();
      int regZero = fresh();
      int regAddr = fresh();
      int regComp = fresh();
      ir.genMoveTempConst(regZero, 0);
      ir.genMoveTempConst(regLoop, 1);
      String loopLabel = freshLabel();
      String endLabel = freshLabel();
      ir.gen(loopLabel);
      ir.genBinOp(regComp, "LE", regLoop, "TEMP " + regSizeOG);
      ir.genCJump(regComp, endLabel);
      ir.genBinOp(regAddr, "TIMES", regLoop, "4");
      ir.genBinOp(regAddr, "PLUS", regAddr, "TEMP " + regAns);
      ir.genHStore(regAddr, 0, regZero);
      ir.genBinOp(regLoop, "PLUS", regLoop, "1");
      ir.genJump(loopLabel);
      ir.gen(endLabel);

      addr.put(n, regAns);

      return Integer.toString(regSize);
   }

   /**
    * f0 -> "new"
    * f1 -> Identifier()
    * f2 -> "("
    * f3 -> ")"
    */
   public String visit(AllocationExpression n, String argu) {
      String _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, "Allocation");
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);

      if(debug){
         System.out.println("Starting Allocation");
      }

      String objClass = n.f1.f0.toString();
      ClassData objClassData = classData.get(objClass);
      int regAns = fresh();
      int regVTable = fresh();

      // initialise the vtable
      int regFirstFunction = fresh();
      ArrayList<String> functions = objClassData.getMethodLabelList();
      ir.genMoveTempString(regVTable, " HALLOCATE "+(functions.size())*4);
      int tempFunctionNameHolder = fresh();
      ir.genMoveTempTemp(regFirstFunction, regVTable);
      // put the functions in the vtable
      for(int i=0; i<functions.size(); i++){
         ir.genMoveTempString(tempFunctionNameHolder, functions.get(i));
         ir.genHStore(regFirstFunction, 4*i, tempFunctionNameHolder);
      }

      if(debug){
         System.out.println("Finished VTable initialisation");
      }

      // get the size of the class
      int noClassVars = objClassData.getNumberVars();
      ir.genMoveTempString(regAns, " HALLOCATE "+(noClassVars+1)*4);
      int regFirstField = fresh();
      ir.genMoveTempTemp(regFirstField, regAns);
      // put the vtable in the first position
      ir.genHStore(regFirstField, 0, regVTable);
      int regZero = fresh();
      ir.genMoveTempConst(regZero, 0);
      // initialise everything with 0
      for(int i=0; i<noClassVars; i++){
         ir.genHStore(regFirstField, 4*(i+1), regZero);
      }

      if(debug){
         System.out.println("Finished Class initialisation");
      }

      addr.put(n, regAns);

      return "@"+objClass;
   }

   /**
    * f0 -> "!"
    * f1 -> Expression()
    */
   public String visit(NotExpression n, String argu) {
      String _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);

      int regAns = fresh();
      int regExpr = addr.get(n.f1);
      String label1 = freshLabel();
      String label2 = freshLabel();

      ir.genCJump(regExpr, label1);
      ir.genMoveTempString(regAns, "0");
      ir.genJump(label2);
      ir.gen(label1);
      ir.genMoveTempString(regAns, "1");
      ir.gen(label2);

      addr.put(n, regAns);
      return _ret;
   }

   /**
    * f0 -> "("
    * f1 -> Expression()
    * f2 -> ")"
    */
   public String visit(BracketExpression n, String argu) {
      String _ret=null;
      argu = null;   // IMPORTANT
      n.f0.accept(this, argu);
      _ret = n.f1.accept(this, argu);
      n.f2.accept(this, argu);

      // !CHANGE
      int regAns = fresh();
      int regExpr = addr.get(n.f1);
      ir.genMoveTempTemp(regAns, regExpr);
      addr.put(n, regAns);

      return _ret;
   }
}
