//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

public class MakeVTable extends GJNoArguDepthFirst<String>{

    HashMap<String, ClassData> classData;
    String currentClass;
    boolean debug;
    String mainClassName;

    public MakeVTable(boolean debug){
        classData = new HashMap<>();
        currentClass = null;
        this.debug = debug;
        mainClassName = "";
    }

///////////////// PRODUCTIONS //////////////////

/**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "{"
    * f3 -> "public"
    * f4 -> "static"
    * f5 -> "void"
    * f6 -> "main"
    * f7 -> "("
    * f8 -> "String"
    * f9 -> "["
    * f10 -> "]"
    * f11 -> Identifier()
    * f12 -> ")"
    * f13 -> "{"
    * f14 -> PrintStatement()
    * f15 -> "}"
    * f16 -> "}"
    */
   public String visit(MainClass n) {
      n.f1.accept(this);
      mainClassName = n.f1.f0.tokenImage;
      return null;
   }
   
   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "{"
    * f3 -> ( VarDeclaration() )*
    * f4 -> ( MethodDeclaration() )*
    * f5 -> "}"
    */
    public String visit(ClassDeclaration n){
       n.f0.accept(this);
       n.f1.accept(this);
       currentClass = n.f1.f0.tokenImage;
       classData.put(currentClass, new ClassData(currentClass, null));
       n.f2.accept(this);
       n.f3.accept(this);
       n.f4.accept(this);
       n.f5.accept(this);
       currentClass = null;
       return null;
    }

    
   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "extends"
    * f3 -> Identifier()
    * f4 -> "{"
    * f5 -> ( VarDeclaration() )*
    * f6 -> ( MethodDeclaration() )*
    * f7 -> "}"
    */
    public String visit(ClassExtendsDeclaration n){
       n.f0.accept(this);
       n.f1.accept(this);
       currentClass = n.f1.f0.tokenImage;
       n.f2.accept(this);
       n.f3.accept(this);
       classData.put(currentClass, new ClassData(currentClass, n.f3.f0.tokenImage));
       n.f4.accept(this);
       n.f5.accept(this);
       n.f6.accept(this);
       n.f7.accept(this);
       currentClass = null;
       return null;
    }

   /**
    * f0 -> Type()
    * f1 -> Identifier()
    * f2 -> ";"
    */
   public String visit(VarDeclaration n) {
      String retType = n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      classData.get(currentClass).addVar(n.f1.f0.tokenImage, currentClass, retType);
      return null;
   }

   /**
    * f0 -> "public"
    * f1 -> Type()
    * f2 -> Identifier()
    * f3 -> "("
    * f4 -> ( FormalParameterList() )?
    * f5 -> ")"
    * f6 -> "{"
    * f7 -> ( VarDeclaration() )*
    * f8 -> ( Statement() )*
    * f9 -> "return"
    * f10 -> Expression()
    * f11 -> ";"
    * f12 -> "}"
    */
   public String visit(MethodDeclaration n) {
      n.f0.accept(this);
      String retType = n.f1.accept(this);
      n.f2.accept(this);
      classData.get(currentClass).addMethod(n.f2.f0.tokenImage, currentClass, retType);
      return null;
   }

   /**
    * f0 -> ArrayType()
    *       | BooleanType()
    *       | IntegerType()
    *       | Identifier()
    */
   public String visit(Type n) {
      return n.f0.accept(this);
   }

   public String visit(ArrayType n) {
        return "int[]";
   }

   public String visit(BooleanType n) {
        return "boolean";
   }

   public String visit(IntegerType n) {
        return "int";
   }

   public String visit(Identifier n) {
      n.f0.accept(this);
      return n.f0.tokenImage;
   }

   //////////////////// CREATE VTABLES //////////////////////
   void mergeWithAncestor(ClassData curClass){
        String parentClass = curClass.getParent();
        while(parentClass!=null){
            if(mainClassName.equals(parentClass))
                break;
            ClassData parent = classData.get(parentClass);
            curClass.merge(parent);
            parentClass = parent.getParent();
        }
   }

    public void createVTables(){
          for(String className : classData.keySet()){
                ClassData curClass = classData.get(className);
                if(debug){
                    curClass.print();
                    System.out.println("Merging with ancestors");
                    System.out.println("-------------------------------");
                }
                mergeWithAncestor(curClass);
                if(debug){
                    curClass.print();
                    System.out.println("-------------------------------");
                }
          }
    }

    public HashMap<String, ClassData> getClassData(){
        return classData;
    }
}
